# Override the default values of the info endpoint
info:
    app:
        name: ${name}
        description: ${description}
        version: ${version}

# enable shutdown of application via a POST
endpoints:
    shutdown:
        enabled: true
    health:
        sensitive: false    # display full details for non-authenticated requests

# show the banner file during startup
spring:
    main:
        show_banner: true
    # Redis configuration (see RedisProperties for details)
    redis:
        database: 0 # redis relies on 0-based index database names
        host: redis
        port: 6379

    rabbitmq:
        host: rabbitmq
        port: 5672
        username: guest
        password: guest
        virtualHost: /

    groovy:
        template:
            check-template-location: false
    jackson:
        serialization:
            indent_output: true

# specify the port the service should bind to when using the embedded container, a value of 0 will bind to a randomly selected available port
server:
    port: 0

security:
    basic:
        enabled: false

# the context to use for the operation actuators, eg /operations/info
management:
    context-path: /operations
    security:
    enabled: false

# operations shell
shell:
    auth:
        simple:
            user:
                name: operations
                password: operations

# which logback configuration file to use
logging:
    config: classpath:logback.xml

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        preferIpAddress: true

example:
    maxPayloadSize: 10
    requireCorrelationId: true

#---------e Profile specific overrides ----------#

# integration testing
---
spring:
    profiles: integration
    redis:
        host: 192.168.44.50

# live
---
spring:
    profiles: live
    redis:
        host: ????
server:
    port: ????
